title = "Path to Programming Blog"
baseURL = "https://www.path-to-programming.tech"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
disqusShortname = "yourdiscussshortname"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/SDiamante13"
  instagram = ""
  youtube = ""
  github = "https://www.github.com/SDiamante13"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/steven-diamante-6a2b7782/"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-mid-gray"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 5