title = "Path to Programming Blog"
baseURL = "https://www.path-to-programming.tech"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 7 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
disqusShortname = "www-path-to-programming-tech"

[params]
  favicon = ""
  description = ""
  facebook = ""
  twitter = "https://twitter.com/DiamanteSteven"
  instagram = ""
  youtube = ""
  github = "https://www.github.com/SDiamante13"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/steven-diamante-6a2b7782/"
  show_reading_time = true
  cover_dimming_class = "bg-black-40"
  background_color_class = "bg-mid-gray"
  featured_image = ""
  recent_posts_number = 6